---
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    #if: ${{ github.event.pull_request.user.login }} == 'udondan'
    if: >
      github.event.pull_request.user.login == 'udondan' &&
      !${{ contains(github.event.*.labels.*.name, 'autorelease: pending') }} &&
      !${{ contains(github.event.*.labels.*.name, 'autorelease: tagged') }}
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1.0.13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: English
          MODEL: gpt-4-0125-preview
          max_tokens: 4096
