---
name: Publish

on:
  release:
    types:
      - published
  workflow_dispatch:
  pull_request: # for testing, when we change the workflow
    branches:
      - main
    paths:
      - .github/workflows/publish.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: actions/checkout@v4

      - run: |
          make install
          npx tsc -p tsconfig.publish.json

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: ${{ github.event_name == 'pull_request' }}
