---
name: Test

permissions:
  contents: read

concurrency:
  group: test
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDC token for assuming the AWS role
      contents: read # checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org

      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v6
        env:
          cache-name: cache-node-modules
        with:
          path: .npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          make install
          (cd test && make install)

      - name: Linting
        run: make eslint

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test package
        run: make test
        env:
          AWS_REGION: us-east-1

      - name: Test building package
        run: make package
